### ISSUE TITLE
Per Readme you can send a message to yourself in OS X...How?

### ISSUE THREAD

**Issue by juggledad** [BananaAcid/node-red-contrib-sysmessage#1]
In the readme is says:
OSX Message / iMessage
Sends messages through the messages.app to any buddy in your list, including iMessages (Hint: add yourself to send to)

So my question is how do you impliment 'yourself'? I can't figure out how to do it and at least one other hasn't;t been able to eithor. 

I've tried setting the Reciever to:
- my nickname
- my name
- my phone number
- my email

note: if I use someone else information, it works fine. So how do I add myself to send to?

**Comment by BananaAcid** [comment]
Your system must be OSX. Does `osascript -e 'tell application "Messages" to send "Hello World" to "Your Name"'` work at your terminal?
Have you checked the out part for error messages as noted in the docs?

**Comment by juggledad** [comment]
I am running this in OSX
If I do that in terminal I get:

Pauls-mini:~ Paul$ osascript -e 'tell application "Messages" to send "Hello World" to "BananaAcid"'
31:65: execution error: Messages got an error: "Hello World" doesn’t understand the “send” message. (-1708)
Pauls-mini:~ Paul$

**Comment by juggledad** [comment]
If I use this syntax:
 osascript -e 'tell application "Messages" to send "this is a test" to buddy "Dampa"'

I get this error:
31:69: execution error: Messages got an error: Can't send a message to yourself. (1)

Note, if I use another buddy it works fine.

**Comment by BananaAcid** [comment]
I will close this issue, as it has not changed - OSX message won't allow sending to yourself :/ was possible once. I am sorry.
